---
- hosts: all
  become: true
  vars:
    storage_safe_mode: false  # true -> no data will be removed unless explicitly requested
    mount_dir: '/opt/test1'
    disk: '/dev/sdc'

  tasks:
    - include_role:
        name: linux-system-roles.storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            disks: ["{{ disk }}"]
            mount_point: "{{ mount_dir }}"
            state: present
      tags:
        - setup

    - include_role:
        name: linux-system-roles.storage
      vars:
        storage_volumes:
          - name: test1
            type: disk
            disks: ["{{ disk }}"]
            mount_point: "{{ mount_dir }}"
            state: absent
      tags:
        - cleanup
