---
- hosts: all
  become: true
  vars:
    storage_safe_mode: false  # defaults to true, in which case no data will be removed unless explicitly requested
    mount_dir: '/opt/vol1'
    disks: ['sdd', 'sde']

  tasks:
    - include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
          - name: testpool1
            disks: "{{ disks }}"
            raid_level: raid1
            encryption: true
            encryption_password: "{{ password }}"
            volumes:
              - name: data
                size: 10g
                mount_point: "{{ mount_dir }}"
      tags:
        - setup

    - include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
          - name: testpool1
            disks: "{{ disks }}"
            state: absent
      tags:
        - cleanup
